// GENERADO por tool/gen_phosphor_glyphs.py — no editar a mano.
// Phosphor Icons (MIT, ver assets/fonts/phosphor/LICENSE). Fuentes en
// assets/fonts/phosphor/*.ttf, códigos de phosphor_flutter 2.1.0.
import 'package:flutter/widgets.dart';

/// Glifo de Phosphor en sus dos estilos: regular (línea) y duotono
/// (trazo [duoPrimary] + relleno suave [duoSecondary]).
class PhGlyph {
  final IconData regular;
  final IconData duoPrimary;
  final IconData duoSecondary;
  const PhGlyph(this.regular, this.duoPrimary, this.duoSecondary);
}

const _reg = 'PhosphorRegular';
const _duo = 'PhosphorDuotone';

class Ph {
  static const alarm = PhGlyph(IconData(0xe006, fontFamily: _reg), IconData(0xe007, fontFamily: _duo), IconData(0xe006, fontFamily: _duo));
  static const androidLogo = PhGlyph(IconData(0xe008, fontFamily: _reg), IconData(0xe009, fontFamily: _duo), IconData(0xe008, fontFamily: _duo));
  static const appleLogo = PhGlyph(IconData(0xe516, fontFamily: _reg), IconData(0xe517, fontFamily: _duo), IconData(0xe516, fontFamily: _duo));
  static const arrowBendUpLeft = PhGlyph(IconData(0xe024, fontFamily: _reg), IconData(0xe025, fontFamily: _duo), IconData(0xe024, fontFamily: _duo));
  static const arrowDown = PhGlyph(IconData(0xe03e, fontFamily: _reg), IconData(0xe03f, fontFamily: _duo), IconData(0xe03e, fontFamily: _duo));
  static const arrowRight = PhGlyph(IconData(0xe06c, fontFamily: _reg), IconData(0xe06d, fontFamily: _duo), IconData(0xe06c, fontFamily: _duo));
  static const arrowSquareOut = PhGlyph(IconData(0xe5de, fontFamily: _reg), IconData(0xe5df, fontFamily: _duo), IconData(0xe5de, fontFamily: _duo));
  static const arrowUUpLeft = PhGlyph(IconData(0xe08a, fontFamily: _reg), IconData(0xe08b, fontFamily: _duo), IconData(0xe08a, fontFamily: _duo));
  static const arrowUp = PhGlyph(IconData(0xe08e, fontFamily: _reg), IconData(0xe08f, fontFamily: _duo), IconData(0xe08e, fontFamily: _duo));
  static const arrowsClockwise = PhGlyph(IconData(0xe094, fontFamily: _reg), IconData(0xe095, fontFamily: _duo), IconData(0xe094, fontFamily: _duo));
  static const arrowsDownUp = PhGlyph(IconData(0xe098, fontFamily: _reg), IconData(0xe099, fontFamily: _duo), IconData(0xe098, fontFamily: _duo));
  static const arrowsLeftRight = PhGlyph(IconData(0xe0a0, fontFamily: _reg), IconData(0xe0a1, fontFamily: _duo), IconData(0xe0a0, fontFamily: _duo));
  static const baby = PhGlyph(IconData(0xe774, fontFamily: _reg), IconData(0xe775, fontFamily: _duo), IconData(0xe774, fontFamily: _duo));
  static const bank = PhGlyph(IconData(0xe0b4, fontFamily: _reg), IconData(0xe0b5, fontFamily: _duo), IconData(0xe0b4, fontFamily: _duo));
  static const barbell = PhGlyph(IconData(0xe0b6, fontFamily: _reg), IconData(0xe0b7, fontFamily: _duo), IconData(0xe0b6, fontFamily: _duo));
  static const bathtub = PhGlyph(IconData(0xe81e, fontFamily: _reg), IconData(0xe81f, fontFamily: _duo), IconData(0xe81e, fontFamily: _duo));
  static const bell = PhGlyph(IconData(0xe0ce, fontFamily: _reg), IconData(0xe0cf, fontFamily: _duo), IconData(0xe0ce, fontFamily: _duo));
  static const bone = PhGlyph(IconData(0xe7f2, fontFamily: _reg), IconData(0xe7f3, fontFamily: _duo), IconData(0xe7f2, fontFamily: _duo));
  static const bookOpen = PhGlyph(IconData(0xe0e6, fontFamily: _reg), IconData(0xe0e7, fontFamily: _duo), IconData(0xe0e6, fontFamily: _duo));
  static const bowlFood = PhGlyph(IconData(0xeaa4, fontFamily: _reg), IconData(0xeaa5, fontFamily: _duo), IconData(0xeaa4, fontFamily: _duo));
  static const briefcase = PhGlyph(IconData(0xe0ee, fontFamily: _reg), IconData(0xe0ef, fontFamily: _duo), IconData(0xe0ee, fontFamily: _duo));
  static const buildings = PhGlyph(IconData(0xe102, fontFamily: _reg), IconData(0xe105, fontFamily: _duo), IconData(0xe102, fontFamily: _duo));
  static const cake = PhGlyph(IconData(0xe780, fontFamily: _reg), IconData(0xe781, fontFamily: _duo), IconData(0xe780, fontFamily: _duo));
  static const calculator = PhGlyph(IconData(0xe538, fontFamily: _reg), IconData(0xe539, fontFamily: _duo), IconData(0xe538, fontFamily: _duo));
  static const calendarBlank = PhGlyph(IconData(0xe10a, fontFamily: _reg), IconData(0xe10b, fontFamily: _duo), IconData(0xe10a, fontFamily: _duo));
  static const calendarDots = PhGlyph(IconData(0xe7b4, fontFamily: _reg), IconData(0xe7b5, fontFamily: _duo), IconData(0xe7b4, fontFamily: _duo));
  static const camera = PhGlyph(IconData(0xe10e, fontFamily: _reg), IconData(0xe10f, fontFamily: _duo), IconData(0xe10e, fontFamily: _duo));
  static const car = PhGlyph(IconData(0xe112, fontFamily: _reg), IconData(0xe113, fontFamily: _duo), IconData(0xe112, fontFamily: _duo));
  static const caretDown = PhGlyph(IconData(0xe136, fontFamily: _reg), IconData(0xe137, fontFamily: _duo), IconData(0xe136, fontFamily: _duo));
  static const caretLeft = PhGlyph(IconData(0xe138, fontFamily: _reg), IconData(0xe139, fontFamily: _duo), IconData(0xe138, fontFamily: _duo));
  static const caretRight = PhGlyph(IconData(0xe13a, fontFamily: _reg), IconData(0xe13b, fontFamily: _duo), IconData(0xe13a, fontFamily: _duo));
  static const caretUp = PhGlyph(IconData(0xe13c, fontFamily: _reg), IconData(0xe13d, fontFamily: _duo), IconData(0xe13c, fontFamily: _duo));
  static const cat = PhGlyph(IconData(0xe748, fontFamily: _reg), IconData(0xe749, fontFamily: _duo), IconData(0xe748, fontFamily: _duo));
  static const certificate = PhGlyph(IconData(0xe766, fontFamily: _reg), IconData(0xe767, fontFamily: _duo), IconData(0xe766, fontFamily: _duo));
  static const chartLineUp = PhGlyph(IconData(0xe156, fontFamily: _reg), IconData(0xe157, fontFamily: _duo), IconData(0xe156, fontFamily: _duo));
  static const chatCircleDots = PhGlyph(IconData(0xe16c, fontFamily: _reg), IconData(0xe16d, fontFamily: _duo), IconData(0xe16c, fontFamily: _duo));
  static const check = PhGlyph(IconData(0xe182, fontFamily: _reg), IconData(0xe183, fontFamily: _duo), IconData(0xe182, fontFamily: _duo));
  static const checkCircle = PhGlyph(IconData(0xe184, fontFamily: _reg), IconData(0xe185, fontFamily: _duo), IconData(0xe184, fontFamily: _duo));
  static const checkSquare = PhGlyph(IconData(0xe186, fontFamily: _reg), IconData(0xe187, fontFamily: _duo), IconData(0xe186, fontFamily: _duo));
  static const checks = PhGlyph(IconData(0xe53a, fontFamily: _reg), IconData(0xe53b, fontFamily: _duo), IconData(0xe53a, fontFamily: _duo));
  static const circle = PhGlyph(IconData(0xe18a, fontFamily: _reg), IconData(0xe18b, fontFamily: _duo), IconData(0xe18a, fontFamily: _duo));
  static const clipboardText = PhGlyph(IconData(0xe198, fontFamily: _reg), IconData(0xe199, fontFamily: _duo), IconData(0xe198, fontFamily: _duo));
  static const clock = PhGlyph(IconData(0xe19a, fontFamily: _reg), IconData(0xe19b, fontFamily: _duo), IconData(0xe19a, fontFamily: _duo));
  static const clockCounterClockwise = PhGlyph(IconData(0xe1a0, fontFamily: _reg), IconData(0xe1a1, fontFamily: _duo), IconData(0xe1a0, fontFamily: _duo));
  static const cloudSun = PhGlyph(IconData(0xe540, fontFamily: _reg), IconData(0xe541, fontFamily: _duo), IconData(0xe540, fontFamily: _duo));
  static const confetti = PhGlyph(IconData(0xe81a, fontFamily: _reg), IconData(0xe81b, fontFamily: _duo), IconData(0xe81a, fontFamily: _duo));
  static const copy = PhGlyph(IconData(0xe1ca, fontFamily: _reg), IconData(0xe1cb, fontFamily: _duo), IconData(0xe1ca, fontFamily: _duo));
  static const couch = PhGlyph(IconData(0xe7f6, fontFamily: _reg), IconData(0xe7f7, fontFamily: _duo), IconData(0xe7f6, fontFamily: _duo));
  static const creditCard = PhGlyph(IconData(0xe1d2, fontFamily: _reg), IconData(0xe1d3, fontFamily: _duo), IconData(0xe1d2, fontFamily: _duo));
  static const crosshair = PhGlyph(IconData(0xe1d6, fontFamily: _reg), IconData(0xe1d7, fontFamily: _duo), IconData(0xe1d6, fontFamily: _duo));
  static const desktop = PhGlyph(IconData(0xe560, fontFamily: _reg), IconData(0xe561, fontFamily: _duo), IconData(0xe560, fontFamily: _duo));
  static const deviceMobile = PhGlyph(IconData(0xe1e0, fontFamily: _reg), IconData(0xe1e1, fontFamily: _duo), IconData(0xe1e0, fontFamily: _duo));
  static const dog = PhGlyph(IconData(0xe74a, fontFamily: _reg), IconData(0xe74b, fontFamily: _duo), IconData(0xe74a, fontFamily: _duo));
  static const door = PhGlyph(IconData(0xe61c, fontFamily: _reg), IconData(0xe61d, fontFamily: _duo), IconData(0xe61c, fontFamily: _duo));
  static const dotsThreeVertical = PhGlyph(IconData(0xe208, fontFamily: _reg), IconData(0xe209, fontFamily: _duo), IconData(0xe208, fontFamily: _duo));
  static const downloadSimple = PhGlyph(IconData(0xe20c, fontFamily: _reg), IconData(0xe20d, fontFamily: _duo), IconData(0xe20c, fontFamily: _duo));
  static const drop = PhGlyph(IconData(0xe210, fontFamily: _reg), IconData(0xe211, fontFamily: _duo), IconData(0xe210, fontFamily: _duo));
  static const envelope = PhGlyph(IconData(0xe214, fontFamily: _reg), IconData(0xe215, fontFamily: _duo), IconData(0xe214, fontFamily: _duo));
  static const eye = PhGlyph(IconData(0xe220, fontFamily: _reg), IconData(0xe221, fontFamily: _duo), IconData(0xe220, fontFamily: _duo));
  static const eyeSlash = PhGlyph(IconData(0xe224, fontFamily: _reg), IconData(0xe225, fontFamily: _duo), IconData(0xe224, fontFamily: _duo));
  static const facebookLogo = PhGlyph(IconData(0xe226, fontFamily: _reg), IconData(0xe227, fontFamily: _duo), IconData(0xe226, fontFamily: _duo));
  static const fileText = PhGlyph(IconData(0xe23a, fontFamily: _reg), IconData(0xe23b, fontFamily: _duo), IconData(0xe23a, fontFamily: _duo));
  static const fingerprint = PhGlyph(IconData(0xe23e, fontFamily: _reg), IconData(0xe23f, fontFamily: _duo), IconData(0xe23e, fontFamily: _duo));
  static const flag = PhGlyph(IconData(0xe244, fontFamily: _reg), IconData(0xe245, fontFamily: _duo), IconData(0xe244, fontFamily: _duo));
  static const flashlight = PhGlyph(IconData(0xe246, fontFamily: _reg), IconData(0xe247, fontFamily: _duo), IconData(0xe246, fontFamily: _duo));
  static const gavel = PhGlyph(IconData(0xea32, fontFamily: _reg), IconData(0xea33, fontFamily: _duo), IconData(0xea32, fontFamily: _duo));
  static const gear = PhGlyph(IconData(0xe270, fontFamily: _reg), IconData(0xe271, fontFamily: _duo), IconData(0xe270, fontFamily: _duo));
  static const genderIntersex = PhGlyph(IconData(0xe6e6, fontFamily: _reg), IconData(0xe6e7, fontFamily: _duo), IconData(0xe6e6, fontFamily: _duo));
  static const gift = PhGlyph(IconData(0xe276, fontFamily: _reg), IconData(0xe277, fontFamily: _duo), IconData(0xe276, fontFamily: _duo));
  static const globe = PhGlyph(IconData(0xe288, fontFamily: _reg), IconData(0xe289, fontFamily: _duo), IconData(0xe288, fontFamily: _duo));
  static const graduationCap = PhGlyph(IconData(0xe62c, fontFamily: _reg), IconData(0xe62d, fontFamily: _duo), IconData(0xe62c, fontFamily: _duo));
  static const handHeart = PhGlyph(IconData(0xe810, fontFamily: _reg), IconData(0xe811, fontFamily: _duo), IconData(0xe810, fontFamily: _duo));
  static const handTap = PhGlyph(IconData(0xec90, fontFamily: _reg), IconData(0xec91, fontFamily: _duo), IconData(0xec90, fontFamily: _duo));
  static const handshake = PhGlyph(IconData(0xe582, fontFamily: _reg), IconData(0xe583, fontFamily: _duo), IconData(0xe582, fontFamily: _duo));
  static const headset = PhGlyph(IconData(0xe584, fontFamily: _reg), IconData(0xe585, fontFamily: _duo), IconData(0xe584, fontFamily: _duo));
  static const heart = PhGlyph(IconData(0xe2a8, fontFamily: _reg), IconData(0xe2a9, fontFamily: _duo), IconData(0xe2a8, fontFamily: _duo));
  static const heartbeat = PhGlyph(IconData(0xe2ac, fontFamily: _reg), IconData(0xe2ad, fontFamily: _duo), IconData(0xe2ac, fontFamily: _duo));
  static const hourglassMedium = PhGlyph(IconData(0xe2b8, fontFamily: _reg), IconData(0xe2b9, fontFamily: _duo), IconData(0xe2b8, fontFamily: _duo));
  static const house = PhGlyph(IconData(0xe2c2, fontFamily: _reg), IconData(0xe2c3, fontFamily: _duo), IconData(0xe2c2, fontFamily: _duo));
  static const identificationCard = PhGlyph(IconData(0xe2c8, fontFamily: _reg), IconData(0xe2c9, fontFamily: _duo), IconData(0xe2c8, fontFamily: _duo));
  static const image = PhGlyph(IconData(0xe2ca, fontFamily: _reg), IconData(0xe2cb, fontFamily: _duo), IconData(0xe2ca, fontFamily: _duo));
  static const imageBroken = PhGlyph(IconData(0xe7a8, fontFamily: _reg), IconData(0xe7a9, fontFamily: _duo), IconData(0xe7a8, fontFamily: _duo));
  static const info = PhGlyph(IconData(0xe2ce, fontFamily: _reg), IconData(0xe2cf, fontFamily: _duo), IconData(0xe2ce, fontFamily: _duo));
  static const lightbulb = PhGlyph(IconData(0xe2dc, fontFamily: _reg), IconData(0xe2dd, fontFamily: _duo), IconData(0xe2dc, fontFamily: _duo));
  static const linkBreak = PhGlyph(IconData(0xe2e4, fontFamily: _reg), IconData(0xe2e5, fontFamily: _duo), IconData(0xe2e4, fontFamily: _duo));
  static const list = PhGlyph(IconData(0xe2f0, fontFamily: _reg), IconData(0xe2f1, fontFamily: _duo), IconData(0xe2f0, fontFamily: _duo));
  static const listChecks = PhGlyph(IconData(0xeadc, fontFamily: _reg), IconData(0xeadd, fontFamily: _duo), IconData(0xeadc, fontFamily: _duo));
  static const lockKey = PhGlyph(IconData(0xe2fe, fontFamily: _reg), IconData(0xe2ff, fontFamily: _duo), IconData(0xe2fe, fontFamily: _duo));
  static const lockKeyOpen = PhGlyph(IconData(0xe300, fontFamily: _reg), IconData(0xe301, fontFamily: _duo), IconData(0xe300, fontFamily: _duo));
  static const magnifyingGlass = PhGlyph(IconData(0xe30c, fontFamily: _reg), IconData(0xe30d, fontFamily: _duo), IconData(0xe30c, fontFamily: _duo));
  static const magnifyingGlassPlus = PhGlyph(IconData(0xe310, fontFamily: _reg), IconData(0xe311, fontFamily: _duo), IconData(0xe310, fontFamily: _duo));
  static const mapPin = PhGlyph(IconData(0xe316, fontFamily: _reg), IconData(0xe317, fontFamily: _duo), IconData(0xe316, fontFamily: _duo));
  static const mapTrifold = PhGlyph(IconData(0xe31a, fontFamily: _reg), IconData(0xe31b, fontFamily: _duo), IconData(0xe31a, fontFamily: _duo));
  static const medal = PhGlyph(IconData(0xe320, fontFamily: _reg), IconData(0xe321, fontFamily: _duo), IconData(0xe320, fontFamily: _duo));
  static const megaphone = PhGlyph(IconData(0xe324, fontFamily: _reg), IconData(0xe325, fontFamily: _duo), IconData(0xe324, fontFamily: _duo));
  static const minusCircle = PhGlyph(IconData(0xe32c, fontFamily: _reg), IconData(0xe32d, fontFamily: _duo), IconData(0xe32c, fontFamily: _duo));
  static const moon = PhGlyph(IconData(0xe330, fontFamily: _reg), IconData(0xe331, fontFamily: _duo), IconData(0xe330, fontFamily: _duo));
  static const navigationArrow = PhGlyph(IconData(0xeade, fontFamily: _reg), IconData(0xeadf, fontFamily: _duo), IconData(0xeade, fontFamily: _duo));
  static const notepad = PhGlyph(IconData(0xe63e, fontFamily: _reg), IconData(0xe63f, fontFamily: _duo), IconData(0xe63e, fontFamily: _duo));
  static const palette = PhGlyph(IconData(0xe6c8, fontFamily: _reg), IconData(0xe6c9, fontFamily: _duo), IconData(0xe6c8, fontFamily: _duo));
  static const paperPlaneTilt = PhGlyph(IconData(0xe398, fontFamily: _reg), IconData(0xe399, fontFamily: _duo), IconData(0xe398, fontFamily: _duo));
  static const path = PhGlyph(IconData(0xe39c, fontFamily: _reg), IconData(0xe39d, fontFamily: _duo), IconData(0xe39c, fontFamily: _duo));
  static const pause = PhGlyph(IconData(0xe39e, fontFamily: _reg), IconData(0xe39f, fontFamily: _duo), IconData(0xe39e, fontFamily: _duo));
  static const pawPrint = PhGlyph(IconData(0xe648, fontFamily: _reg), IconData(0xe649, fontFamily: _duo), IconData(0xe648, fontFamily: _duo));
  static const pencilSimple = PhGlyph(IconData(0xe3b4, fontFamily: _reg), IconData(0xe3b5, fontFamily: _duo), IconData(0xe3b4, fontFamily: _duo));
  static const percent = PhGlyph(IconData(0xe3b6, fontFamily: _reg), IconData(0xe3b7, fontFamily: _duo), IconData(0xe3b6, fontFamily: _duo));
  static const phone = PhGlyph(IconData(0xe3b8, fontFamily: _reg), IconData(0xe3b9, fontFamily: _duo), IconData(0xe3b8, fontFamily: _duo));
  static const pill = PhGlyph(IconData(0xe700, fontFamily: _reg), IconData(0xe701, fontFamily: _duo), IconData(0xe700, fontFamily: _duo));
  static const play = PhGlyph(IconData(0xe3d0, fontFamily: _reg), IconData(0xe3d1, fontFamily: _duo), IconData(0xe3d0, fontFamily: _duo));
  static const plus = PhGlyph(IconData(0xe3d4, fontFamily: _reg), IconData(0xe3d5, fontFamily: _duo), IconData(0xe3d4, fontFamily: _duo));
  static const prohibit = PhGlyph(IconData(0xe3de, fontFamily: _reg), IconData(0xe3df, fontFamily: _duo), IconData(0xe3de, fontFamily: _duo));
  static const qrCode = PhGlyph(IconData(0xe3e6, fontFamily: _reg), IconData(0xe3e7, fontFamily: _duo), IconData(0xe3e6, fontFamily: _duo));
  static const question = PhGlyph(IconData(0xe3e8, fontFamily: _reg), IconData(0xe3eb, fontFamily: _duo), IconData(0xe3e8, fontFamily: _duo));
  static const radioButton = PhGlyph(IconData(0xeb08, fontFamily: _reg), IconData(0xeb09, fontFamily: _duo), IconData(0xeb08, fontFamily: _duo));
  static const receipt = PhGlyph(IconData(0xe3ec, fontFamily: _reg), IconData(0xe3f1, fontFamily: _duo), IconData(0xe3ec, fontFamily: _duo));
  static const rocketLaunch = PhGlyph(IconData(0xe3fe, fontFamily: _reg), IconData(0xe401, fontFamily: _duo), IconData(0xe3fe, fontFamily: _duo));
  static const ruler = PhGlyph(IconData(0xe6b8, fontFamily: _reg), IconData(0xe6b9, fontFamily: _duo), IconData(0xe6b8, fontFamily: _duo));
  static const scales = PhGlyph(IconData(0xe750, fontFamily: _reg), IconData(0xe751, fontFamily: _duo), IconData(0xe750, fontFamily: _duo));
  static const scroll = PhGlyph(IconData(0xeb7a, fontFamily: _reg), IconData(0xeb7b, fontFamily: _duo), IconData(0xeb7a, fontFamily: _duo));
  static const sealCheck = PhGlyph(IconData(0xe606, fontFamily: _reg), IconData(0xe607, fontFamily: _duo), IconData(0xe606, fontFamily: _duo));
  static const shareNetwork = PhGlyph(IconData(0xe408, fontFamily: _reg), IconData(0xe40b, fontFamily: _duo), IconData(0xe408, fontFamily: _duo));
  static const shieldCheck = PhGlyph(IconData(0xe40c, fontFamily: _reg), IconData(0xe40f, fontFamily: _duo), IconData(0xe40c, fontFamily: _duo));
  static const signIn = PhGlyph(IconData(0xe428, fontFamily: _reg), IconData(0xe429, fontFamily: _duo), IconData(0xe428, fontFamily: _duo));
  static const signOut = PhGlyph(IconData(0xe42a, fontFamily: _reg), IconData(0xe42b, fontFamily: _duo), IconData(0xe42a, fontFamily: _duo));
  static const siren = PhGlyph(IconData(0xe9b8, fontFamily: _reg), IconData(0xe9b9, fontFamily: _duo), IconData(0xe9b8, fontFamily: _duo));
  static const slidersHorizontal = PhGlyph(IconData(0xe434, fontFamily: _reg), IconData(0xe435, fontFamily: _duo), IconData(0xe434, fontFamily: _duo));
  static const sparkle = PhGlyph(IconData(0xe6a2, fontFamily: _reg), IconData(0xe6a3, fontFamily: _duo), IconData(0xe6a2, fontFamily: _duo));
  static const square = PhGlyph(IconData(0xe45e, fontFamily: _reg), IconData(0xe45f, fontFamily: _duo), IconData(0xe45e, fontFamily: _duo));
  static const squaresFour = PhGlyph(IconData(0xe464, fontFamily: _reg), IconData(0xe465, fontFamily: _duo), IconData(0xe464, fontFamily: _duo));
  static const star = PhGlyph(IconData(0xe46a, fontFamily: _reg), IconData(0xe46b, fontFamily: _duo), IconData(0xe46a, fontFamily: _duo));
  static const stethoscope = PhGlyph(IconData(0xe7ea, fontFamily: _reg), IconData(0xe7eb, fontFamily: _duo), IconData(0xe7ea, fontFamily: _duo));
  static const storefront = PhGlyph(IconData(0xe470, fontFamily: _reg), IconData(0xe471, fontFamily: _duo), IconData(0xe470, fontFamily: _duo));
  static const sun = PhGlyph(IconData(0xe472, fontFamily: _reg), IconData(0xe473, fontFamily: _duo), IconData(0xe472, fontFamily: _duo));
  static const sunHorizon = PhGlyph(IconData(0xe5b6, fontFamily: _reg), IconData(0xe5b7, fontFamily: _duo), IconData(0xe5b6, fontFamily: _duo));
  static const syringe = PhGlyph(IconData(0xe968, fontFamily: _reg), IconData(0xe969, fontFamily: _duo), IconData(0xe968, fontFamily: _duo));
  static const tag = PhGlyph(IconData(0xe478, fontFamily: _reg), IconData(0xe479, fontFamily: _duo), IconData(0xe478, fontFamily: _duo));
  static const tennisBall = PhGlyph(IconData(0xe720, fontFamily: _reg), IconData(0xe721, fontFamily: _duo), IconData(0xe720, fontFamily: _duo));
  static const thumbsDown = PhGlyph(IconData(0xe48c, fontFamily: _reg), IconData(0xe48d, fontFamily: _duo), IconData(0xe48c, fontFamily: _duo));
  static const thumbsUp = PhGlyph(IconData(0xe48e, fontFamily: _reg), IconData(0xe48f, fontFamily: _duo), IconData(0xe48e, fontFamily: _duo));
  static const timer = PhGlyph(IconData(0xe492, fontFamily: _reg), IconData(0xe493, fontFamily: _duo), IconData(0xe492, fontFamily: _duo));
  static const trash = PhGlyph(IconData(0xe4a6, fontFamily: _reg), IconData(0xe4a7, fontFamily: _duo), IconData(0xe4a6, fontFamily: _duo));
  static const tree = PhGlyph(IconData(0xe6da, fontFamily: _reg), IconData(0xe6db, fontFamily: _duo), IconData(0xe6da, fontFamily: _duo));
  static const uploadSimple = PhGlyph(IconData(0xe4c0, fontFamily: _reg), IconData(0xe4c1, fontFamily: _duo), IconData(0xe4c0, fontFamily: _duo));
  static const user = PhGlyph(IconData(0xe4c2, fontFamily: _reg), IconData(0xe4c3, fontFamily: _duo), IconData(0xe4c2, fontFamily: _duo));
  static const userCircle = PhGlyph(IconData(0xe4c4, fontFamily: _reg), IconData(0xe4c5, fontFamily: _duo), IconData(0xe4c4, fontFamily: _duo));
  static const userFocus = PhGlyph(IconData(0xe6fc, fontFamily: _reg), IconData(0xe6fd, fontFamily: _duo), IconData(0xe6fc, fontFamily: _duo));
  static const userPlus = PhGlyph(IconData(0xe4d0, fontFamily: _reg), IconData(0xe4d1, fontFamily: _duo), IconData(0xe4d0, fontFamily: _duo));
  static const users = PhGlyph(IconData(0xe4d6, fontFamily: _reg), IconData(0xe4d7, fontFamily: _duo), IconData(0xe4d6, fontFamily: _duo));
  static const videoCamera = PhGlyph(IconData(0xe4da, fontFamily: _reg), IconData(0xe4db, fontFamily: _duo), IconData(0xe4da, fontFamily: _duo));
  static const wallet = PhGlyph(IconData(0xe68a, fontFamily: _reg), IconData(0xe68b, fontFamily: _duo), IconData(0xe68a, fontFamily: _duo));
  static const warning = PhGlyph(IconData(0xe4e0, fontFamily: _reg), IconData(0xe4e1, fontFamily: _duo), IconData(0xe4e0, fontFamily: _duo));
  static const warningCircle = PhGlyph(IconData(0xe4e2, fontFamily: _reg), IconData(0xe4e3, fontFamily: _duo), IconData(0xe4e2, fontFamily: _duo));
  static const wifiSlash = PhGlyph(IconData(0xe4f2, fontFamily: _reg), IconData(0xe4f3, fontFamily: _duo), IconData(0xe4f2, fontFamily: _duo));
  static const wrench = PhGlyph(IconData(0xe5d4, fontFamily: _reg), IconData(0xe5d5, fontFamily: _duo), IconData(0xe5d4, fontFamily: _duo));
  static const x = PhGlyph(IconData(0xe4f6, fontFamily: _reg), IconData(0xe4f7, fontFamily: _duo), IconData(0xe4f6, fontFamily: _duo));
  static const xCircle = PhGlyph(IconData(0xe4f8, fontFamily: _reg), IconData(0xe4f9, fontFamily: _duo), IconData(0xe4f8, fontFamily: _duo));

  Ph._();
}
