[phases.setup]
nixPkgs = ["node", "npm"]

[phases.install]
cmds = ["cd garden-api && npm ci"]

[phases.build]
cmds = ["cd garden-api && npm run build && npx prisma generate"]

[start]
cmd = "cd garden-api && node dist/server.js"
